language: php

php:
  - 5.6
  - 7.0
  - nightly
  - hhvm

before_script:
  - composer require symfony/dom-crawler:dev-master symfony/css-selector:dev-master
  - composer install

script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] ; then ./vendor/bin/phpcs --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml ./src/ ; fi'
  - phpunit --exclude-group performance

cache:
  directories:
    - vendor/
