language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - php `which composer` require symfony/dom-crawler:dev-master symfony/css-selector:dev-master
  - php `which composer` install

script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] ; then ./vendor/bin/phpcs --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml ./src/ ; fi'
  - phpunit --exclude-group performance
